name: vatt
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
# Install cuda libs + ptxas compiler from nvidia channel
# This will accelerate the compilation of kernels for your specific card
  - cudatoolkit=11.2
  - cudnn=8.1
  - pip
  - pip:
     - tensorflow==2.7.0
     - tensorflow-gpu==2.7.0
     - tensorflow-addons==0.15.0
     - tensorflow-probability==0.15.0
     - tensorflow_text==2.7.0
     - keras==2.7.0
     - scikit-image
     - scikit-learn
     - scipy
     - six
     - numpy
     - PyYAML
     - absl-py
     - git+git://github.com/deepmind/dmvr.git
variables:
  # Adjust to point to your local env path:
  LD_LIBRARY_PATH: /home/jaqa/.conda/envs/vatt/lib
